### ISSUE TITLE
disable logging to logfile via options

### ISSUE THREAD

**Issue by gurvindersingh** [jpmens/stash53#5]
I am interested in stash53 to parse the packets, generate the json document and ship it to logstash. it should not log to logfile as it generated unnecessary IO traffic.

Thanks for nice tool :-)
- G

**Comment by jpmens** [comment]
Indeed, you're right. That's an easy one.

**Comment by jpmens** [comment]
As a matter of curiosity, @gurvindersingh, which emitter (Redis, ZeroMQ, MQTT) will you be using?

**Comment by gurvindersingh** [comment]
I am using Redis emitter and also there is FIXME for key also, which is set to default as dns:hippo

**Comment by jpmens** [comment]
Both fixed in https://github.com/jpmens/stash53/commit/c8fcba1ad757709dcad1f0e5fea939155c6c8c8a
1. Logging to files will only be done if `-l` or `-L` are specified.
2. Redis emitter key now taken from `-O` option.
